[package]
name = "central-repository-dao"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
entity = { path = "../entity" }
validator = { version = "0.16.0", features = ["validator_derive", "derive"] }
log = "0.4.17"
async-trait = "0.1.68"

[dependencies.sea-orm]
version = "0.11.0"
features = ["runtime-tokio-native-tls", "sqlx-postgres"]

#[dev-dependencies]
#tokio = { version = "1.20.0", features = ["macros", "rt"] }

[features]
mock = ["sea-orm/mock"]

